<p><a href="<?php echo $this->url(
    array(
        'controller' => 'account',
        'action'     => 'add'
    ), 
    'default', 
    true) ?>">Sign Our Guestbook</a></p>

Guestbook Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->name) ?></dt>
    <dd><?php echo $this->escape($entry->desc) ?></dd>
    <?php endforeach ?>
</dl>
